favicon: /img/fluid.png
apple_touch_icon: /img/fluid.png

dark_mode:
  enable: true
  default: auto

navbar:
  blog_title: "ZhiYuan"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml

index:
  banner_img: /img/fluid.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  slogan:
    enable: true
    text: "一名热爱编程的大学生"

post:
  banner_img: /img/fluid.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  toc:
    enable: true
  copyright:
    enable: true
    license: 'BY'

about:
  enable: true
  banner_img: /img/fluid.png
  banner_img_height: 50
  avatar: /img/fluid.png
  name: "ZhiYuan"
  intro: "一名热爱编程的大学生"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/1zZhiYuan", tip: "GitHub" }

page404:
  enable: true
  redirect_delay: 5000
